$(document).ready(function(){
    $('#tombol').click(function(){
        $('#modal-box').show(2000);
        $('#background').fadeIn(1000);
    })
    $('#close-button').click(function(){
        $('#modal-box').hide(2000);
        $('#background').fadeOut(1000);
    })
})